name       : raft
version    : 0.17.1
release    : 6
source     :
    - https://github.com/canonical/raft/archive/refs/tags/v0.17.1.tar.gz : e31c7fafbdd5f94913161c5d64341a203364e512524b47295c97a91e83c4198b
license    : LGPL-3.0-only
homepage   : https://github.com/canonical/raft
component  : programming.library
summary    : C implementation of the Raft consensus protocol
description: |
    C implementation of the Raft consensus protocol
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # We only need the library files, but these could be included in the future
    # if there is ever an additional consumer or need for them
    rm -rf ${installdir}/usr/bin
