name       : raft
version    : 0.11.3
release    : 3
source     :
    - https://github.com/canonical/raft/archive/refs/tags/v0.11.3.tar.gz : 82532c001b0fd1eeefb4bb4d333b36ab9476e0652f24ff28c1177b476274b896
license    : LGPL-3.0-only
homepage   : https://github.com/canonical/raft
component  : programming.library
summary    : C implementation of the Raft consensus protocol
description: |
    C implementation of the Raft consensus protocol
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # We only need the library files, but these could be included in the future
    # if there is ever an additional consumer or need for them
    rm -rf ${installdir}/usr/bin
