name       : raft
version    : 0.11.2
release    : 2
source     :
    - https://github.com/canonical/raft/archive/refs/tags/v0.11.2.tar.gz : c89fd6a6fa3c9e6d670b74e389b2d028dfd39d1eec2b18661fae73a9bfd6b89d
license    : LGPL-3.0-only
homepage   : https://github.com/canonical/raft
component  : programming.library
summary    : C implementation of the Raft consensus protocol
description: |
    C implementation of the Raft consensus protocol
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # We only need the library files, but these could be included in the future
    # if there is ever an additional consumer or need for them
    rm -rf ${installdir}/usr/bin
