name       : raft
version    : 0.11.1
release    : 1
source     :
    - https://github.com/canonical/raft/archive/refs/tags/v0.11.1.tar.gz : 9a8dc27c991f365c07a82a2fad5a9a26f842900f3b1586c824442cc652005e4e
license    : LGPL-3.0-only
homepage   : https://github.com/canonical/raft
component  : programming.library
summary    : C implementation of the Raft consensus protocol
description: |
    C implementation of the Raft consensus protocol
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # We only need the library files, but these could be included in the future
    # if there is ever an additional consumer or need for them
    rm -rf ${installdir}/usr/bin
